FROM ubuntu:18.04
RUN apt-get update -y && apt-get install software-properties-common -y  && apt-get upgrade -y && apt-get install curl -y
RUN mkdir /home/pipinstall && mkdir -p /home/flaskapp/MI_CHALLENGE
RUN cd home/pipinstall && apt install python3-pip -y
RUN pip3 install cython
ENV PROJ_DIR /usr/local
RUN pip3 install Flask
ENV FLASK_APP app
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
EXPOSE 5000
WORKDIR /home/flaskapp/MI_CHALLENGE
#COPY requirements.txt /home/flaskapp
COPY . /home/flaskapp/MI_CHALLENGE
#COPY app.py /home/flaskapp
RUN pip3 install -r requirements.pip
CMD ["gunicorn","--bind","0.0.0.0:5000", "mobility.main:app"]